# Generated by Django 4.2.7 on 2023-11-07 19:37

import auths.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='фамилия')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('is_active', models.BooleanField(default=True, verbose_name='статус активности')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='статус администратора')),
                ('is_staff', models.BooleanField(default=False, verbose_name='статус работника')),
                ('datetime_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ('-id',),
            },
            managers=[
                ('objects', auths.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumVitae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='название профессии')),
                ('employment_status', models.CharField(choices=[('NSL', 'Не выбрано'), ('FULL', 'Полная занятость'), ('PART', 'Частичная занятость'), ('VLNT', 'Волонтерство')], default='FULL', max_length=4, verbose_name='занятость')),
                ('category', models.CharField(choices=[('NOT_SELECTED', 'Не выбрано'), ('IT', 'Информаионные технологии'), ('HEALTH', 'Здравохранение'), ('EDUCATION', 'Образование'), ('MANUFACTURING', 'Производство и инженерия'), ('FINANCES', 'Финансы'), ('MARKETING', 'Маркетинг и реклама'), ('HOTEL', 'Гостиничный бизнес'), ('RESTAURANT', 'Ресторанный бизнес'), ('SALES', 'Продажи'), ('ART', 'Искусство'), ('FUN', 'Развлечения'), ('TRANSPORT', 'Транспорт и логистика'), ('BUILDING', 'Строительство и архитектура'), ('AGRICULTURE', 'Сельское хозяйство и сельскохозяйственные науки'), ('UNCOMMERCIAL', 'Некоммерческий сектор'), ('JURISPRUDENCE', 'Юриспруденция и право'), ('SPORT', 'Спорт и физическая активность')], default='NOT_SELECTED', max_length=100, verbose_name='категория')),
                ('business_trip_readiness', models.CharField(choices=[('NSL', 'Не выбрано'), ('YES', 'Да'), ('NO', 'Нет')], default='NSL', max_length=3, verbose_name='готовность к командировкам')),
                ('schedule', models.CharField(choices=[('NOTSELECTED', 'Не выбрано'), ('FULL_DAY', 'Полный день'), ('FLEX', 'Гибкий формат'), ('2x2', '2/2'), ('HALFTIME', 'Половина ставки'), ('REMOTE', 'Удаленная работа'), ('HYBRID', 'Гибридный формат')], default='NOTSELECTED', max_length=12, verbose_name='график работы')),
                ('desired_salary', models.PositiveIntegerField(default=100, verbose_name='желаемая зарплата')),
                ('currency', models.CharField(choices=[('NOTSELECTED', 'Не выбрано'), ('KZT', 'Тенге'), ('RUB', 'Рубли'), ('USD', 'Доллары'), ('EUR', 'Евро'), ('CAD', 'Канадский доллар'), ('GBP', 'Британский фунт'), ('CNH', 'Китайский юань')], default='NOTSELECTED', max_length=12, verbose_name='валюта')),
                ('phone_number', models.CharField(default=None, max_length=100, verbose_name='номер телефона')),
                ('job_email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='почта для связи')),
                ('citizenship', models.CharField(choices=[('NTS', 'Не выбрано'), ('KZ', 'Казахстан'), ('RU', 'Российская Федерация'), ('BEL', 'Беларусь'), ('UA', 'Украина'), ('UZB', 'Узбекистан'), ('GRX', 'Грузия'), ('CHN', 'Китай'), ('AZB', 'Азербайджан'), ('ARM', 'Армения'), ('KRG', 'Кыргызстан'), ('USA', 'Соединенные Штаты Америки'), ('CND', 'Канада'), ('PL', 'Польша'), ('CZR', 'Чехия'), ('GRC', 'Греция'), ('GRM', 'Германия'), ('ITL', 'Италия'), ('GBT', 'Великобритания'), ('FRN', 'Франция'), ('SWD', 'Швеция'), ('SWZ', 'Швейцария'), ('NTL', 'Нидерланды')], default='NTS', max_length=3, verbose_name='гражданство')),
                ('living_place', models.CharField(default='Караганда', max_length=150, verbose_name='город проживания')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cv/', verbose_name='фото')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cv', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'резюме',
                'verbose_name_plural': 'резюме',
                'ordering': ('-id',),
            },
        ),
    ]
