# Generated by Django 4.2.7 on 2023-12-16 12:20

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='jobseeker',
            managers=[
                ('jobseekers', django.db.models.manager.Manager()),
            ],
        ),
    ]
