# Generated by Django 4.2.7 on 2023-11-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumvitae',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cv/', verbose_name='фото'),
        ),
    ]
