# Generated by Django 4.2.7 on 2023-12-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_alter_jobseeker_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('JOBSEEKER', 'Jobseeker'), ('COMPANY', 'Company')], max_length=30, verbose_name='роль'),
        ),
    ]
