# Generated by Django 4.2.7 on 2023-11-14 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_rename_languages_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='publish_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 11, 15, 3, 26, 29, 127088), verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='curriculumvitae',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 11, 15, 3, 26, 29, 127088), null=True, verbose_name='дата рождения'),
        ),
    ]
