# Generated by Django 4.2.7 on 2023-12-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
