# Generated by Django 4.2.7 on 2023-11-18 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0005_alter_curriculumvitae_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumvitae',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 11, 18, 9, 19, 50, 255972), null=True, verbose_name='дата рождения'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='publish_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 11, 18, 9, 19, 50, 255972), verbose_name='дата публикации'),
        ),
    ]
