# Generated by Django 4.2.7 on 2023-11-18 09:22

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0006_alter_curriculumvitae_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumvitae',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата рождения'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='publish_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 11, 18, 15, 22, 4, 630107), verbose_name='дата публикации'),
        ),
    ]
