# Generated by Django 4.2.7 on 2023-12-25 10:40

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumVitae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='название профессии')),
                ('birth_date', models.DateField(auto_now_add=True, verbose_name='дата рождения')),
                ('employment_status', models.CharField(choices=[('NSL', 'Не выбрано'), ('FULL', 'Полная занятость'), ('PART', 'Частичная занятость'), ('VLNT', 'Волонтерство')], default='FULL', max_length=4, verbose_name='занятость')),
                ('category', models.CharField(choices=[('NOT_SELECTED', 'Не выбрано'), ('IT', 'Информаионные технологии'), ('HEALTH', 'Здравохранение'), ('EDUCATION', 'Образование'), ('MANUFACTURING', 'Производство и инженерия'), ('FINANCES', 'Финансы'), ('MARKETING', 'Маркетинг и реклама'), ('HOTEL', 'Гостиничный бизнес'), ('RESTAURANT', 'Ресторанный бизнес'), ('SALES', 'Продажи'), ('ART', 'Искусство'), ('FUN', 'Развлечения'), ('TRANSPORT', 'Транспорт и логистика'), ('BUILDING', 'Строительство и архитектура'), ('AGRICULTURE', 'Сельское хозяйство и сельскохозяйственные науки'), ('UNCOMMERCIAL', 'Некоммерческий сектор'), ('JURISPRUDENCE', 'Юриспруденция и право'), ('SPORT', 'Спорт и физическая активность')], default='NOT_SELECTED', max_length=100, verbose_name='категория')),
                ('business_trip_readiness', models.CharField(choices=[('NSL', 'Не выбрано'), ('YES', 'Да'), ('NO', 'Нет')], default='NSL', max_length=3, verbose_name='готовность к командировкам')),
                ('schedule', models.CharField(choices=[('NOTSELECTED', 'Не выбрано'), ('FULL_DAY', 'Полный день'), ('FLEX', 'Гибкий формат'), ('2x2', '2/2'), ('HALFTIME', 'Половина ставки'), ('REMOTE', 'Удаленная работа'), ('HYBRID', 'Гибридный формат')], default='NOTSELECTED', max_length=12, verbose_name='график работы')),
                ('desired_salary', models.PositiveIntegerField(default=100, verbose_name='желаемая зарплата')),
                ('currency', models.CharField(choices=[('NOTSELECTED', 'Не выбрано'), ('KZT', 'Тенге'), ('RUB', 'Рубли'), ('USD', 'Доллары'), ('EUR', 'Евро'), ('CAD', 'Канадский доллар'), ('GBP', 'Британский фунт'), ('CNH', 'Китайский юань')], default='NOTSELECTED', max_length=12, verbose_name='валюта')),
                ('phone_number', models.CharField(default=None, max_length=100, verbose_name='номер телефона')),
                ('job_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='почта для связи')),
                ('citizenship', models.CharField(choices=[('NTS', 'Не выбрано'), ('KZ', 'Казахстан'), ('RU', 'Российская Федерация'), ('BEL', 'Беларусь'), ('UA', 'Украина'), ('UZB', 'Узбекистан'), ('GRX', 'Грузия'), ('CHN', 'Китай'), ('AZB', 'Азербайджан'), ('ARM', 'Армения'), ('KRG', 'Кыргызстан'), ('USA', 'Соединенные Штаты Америки'), ('CND', 'Канада'), ('PL', 'Польша'), ('CZR', 'Чехия'), ('GRC', 'Греция'), ('GRM', 'Германия'), ('ITL', 'Италия'), ('GBT', 'Великобритания'), ('FRN', 'Франция'), ('SWD', 'Швеция'), ('SWZ', 'Швейцария'), ('NTL', 'Нидерланды')], default='NTS', max_length=3, verbose_name='гражданство')),
                ('living_place', models.CharField(default='Караганда', max_length=150, verbose_name='город проживания')),
                ('education', models.CharField(choices=[('MDM', 'Среднее профессиональное образование'), ('HBC', 'Высшее (бакалавриат)'), ('HMG', 'Высшее (магистратура)'), ('HPH', 'Высшее (докторантура)'), ('NON', 'Нет')], default='NON', max_length=3, verbose_name='образование')),
                ('gender', models.CharField(choices=[('N', 'Не выбрано'), ('M', 'Мужской'), ('W', 'Женский')], default='N', max_length=1, verbose_name='пол')),
                ('family_status', models.CharField(choices=[('N', 'Не выбрано'), ('S', 'Не в браке'), ('M', 'В браке'), ('MH', 'В браке (есть дети)'), ('CP', 'В отношениях')], default='N', max_length=2, verbose_name='семейное положение')),
                ('university', models.CharField(blank=True, max_length=255, null=True, verbose_name='университет')),
                ('university_graduate_year', models.PositiveSmallIntegerField(default=2006, validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2030)], verbose_name='год окончания')),
                ('faculty', models.CharField(blank=True, max_length=150, null=True, verbose_name='факультет')),
                ('speciality', models.CharField(blank=True, max_length=150, null=True, verbose_name='специальность')),
                ('education_form', models.CharField(choices=[('FT', 'Очная'), ('PT', 'Очно-заочная'), ('DL', 'Заочная')], default='FT', max_length=2, verbose_name='форма обучения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cv/', verbose_name='фото')),
                ('coursess', models.TextField(blank=True, help_text='Напишите о курсах, которые проходили(необязательно)', null=True, verbose_name='курсы')),
            ],
            options={
                'verbose_name': 'резюме',
                'verbose_name_plural': 'резюме',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='язык')),
            ],
            options={
                'verbose_name': 'язык',
                'verbose_name_plural': 'языки',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 25, 16, 40, 29, 155685), verbose_name='дата публикации')),
                ('title', models.CharField(max_length=150, verbose_name='название вакансии')),
                ('category', models.CharField(choices=[('NOT_SELECTED', 'Не выбрано'), ('IT', 'Информаионные технологии'), ('HEALTH', 'Здравохранение'), ('EDUCATION', 'Образование'), ('MANUFACTURING', 'Производство и инженерия'), ('FINANCES', 'Финансы'), ('MARKETING', 'Маркетинг и реклама'), ('HOTEL', 'Гостиничный бизнес'), ('RESTAURANT', 'Ресторанный бизнес'), ('SALES', 'Продажи'), ('ART', 'Искусство'), ('FUN', 'Развлечения'), ('TRANSPORT', 'Транспорт и логистика'), ('BUILDING', 'Строительство и архитектура'), ('AGRICULTURE', 'Сельское хозяйство и сельскохозяйственные науки'), ('UNCOMMERCIAL', 'Некоммерческий сектор'), ('JURISPRUDENCE', 'Юриспруденция и право'), ('SPORT', 'Спорт и физическая активность')], default='NOT_SELECTED', max_length=100, verbose_name='категория')),
                ('selery_lower_limit', models.PositiveIntegerField(blank=True, help_text='введите нижний предел зарплаты', null=True, verbose_name='зарплата от')),
                ('selery_upper_limit', models.PositiveIntegerField(blank=True, help_text='введите верхний предел зарплаты', null=True, verbose_name='зарплата до')),
                ('selery_currency', models.CharField(blank=True, choices=[('NOTSELECTED', 'Не выбрано'), ('KZT', 'Тенге'), ('RUB', 'Рубли'), ('USD', 'Доллары'), ('EUR', 'Евро'), ('CAD', 'Канадский доллар'), ('GBP', 'Британский фунт'), ('CNH', 'Китайский юань')], max_length=15, null=True, verbose_name='валюта')),
                ('selery_type', models.CharField(blank=True, choices=[('NETTO', 'Нетто'), ('BRUTTO', 'Брутто')], help_text='выберите тип выплачиваемой зарплаты', max_length=15, null=True, verbose_name='тип зарплаты')),
                ('about_company', models.TextField(help_text='расскажите о вашей компании', verbose_name='о компании')),
                ('responsibilities', models.TextField(help_text='расскажите об обязанностях кандидата', verbose_name='обязанности кандидата')),
                ('specialization', models.TextField(help_text='расскажите о вашей специализации', verbose_name='специализация компании')),
                ('requirements', models.TextField(help_text='расскажите о требованиях к кандидату', verbose_name='требования к кандидату')),
                ('schedule', models.CharField(choices=[('NOTSELECTED', 'Не выбрано'), ('FULL_DAY', 'Полный день'), ('FLEX', 'Гибкий формат'), ('2x2', '2/2'), ('HALFTIME', 'Половина ставки'), ('REMOTE', 'Удаленная работа'), ('HYBRID', 'Гибридный формат')], default='NOTSELECTED', max_length=15, verbose_name='график работы')),
                ('work_experience', models.CharField(choices=[('NO', 'Без опыта'), ('1-3', '1-3 года'), ('3-5', '3-5 лет'), ('5-M', '5 лет и больше')], default='1-3', max_length=5, verbose_name='опыт работы')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancy', to=settings.AUTH_USER_MODEL, verbose_name='компания')),
            ],
            options={
                'verbose_name': 'вакансия',
                'verbose_name_plural': 'вакансии',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='VacancyResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_response', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата и время отклика')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='main.curriculumvitae', verbose_name='резюме')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_responses', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='main.vacancy', verbose_name='вакансия')),
            ],
            options={
                'verbose_name': 'отклик на вакансию',
                'verbose_name_plural': 'отклики на вакансию',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='curriculumvitae',
            name='languages',
            field=models.ManyToManyField(to='main.language', verbose_name='владение языками'),
        ),
        migrations.AddField(
            model_name='curriculumvitae',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cv', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
