# Generated by Django 4.2.7 on 2024-01-13 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='publish_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 1, 14, 4, 6, 11, 247152), verbose_name='дата публикации'),
        ),
    ]
