# Generated by Django 4.2.7 on 2023-12-19 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='selery_lower_limit',
            field=models.PositiveIntegerField(blank=True, help_text='введите нижний предел зарплаты', null=True, verbose_name='зарплата от'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='selery_type',
            field=models.CharField(blank=True, choices=[('NETTO', 'Нетто'), ('BRUTTO', 'Брутто')], help_text='выберите тип выплачиваемой зарплаты', max_length=15, null=True, verbose_name='тип зарплаты'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='selery_upper_limit',
            field=models.PositiveIntegerField(blank=True, help_text='введите верхний предел зарплаты', null=True, verbose_name='зарплата до'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='publish_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 19, 20, 5, 5, 598394), verbose_name='дата публикации'),
        ),
    ]
