# Generated by Django 4.2.7 on 2023-12-25 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='publish_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 25, 16, 53, 8, 946270), verbose_name='дата публикации'),
        ),
    ]
