# Generated by Django 4.2.7 on 2023-12-16 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='publish_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 16, 18, 4, 56, 441375), verbose_name='дата публикации'),
        ),
    ]
