# Generated by Django 4.2.7 on 2023-12-19 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_vacancy_selery_lower_limit_vacancy_selery_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumvitae',
            name='job_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='почта для связи'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='publish_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 19, 20, 27, 11, 636570), verbose_name='дата публикации'),
        ),
    ]
