# Generated by Django 4.2.7 on 2023-12-25 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_categorychoices_alter_vacancy_publish_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumvitae',
            name='category',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='category',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='publish_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 25, 22, 37, 2, 565221), verbose_name='дата публикации'),
        ),
        migrations.AddField(
            model_name='curriculumvitae',
            name='category',
            field=models.ManyToManyField(related_name='cvc', to='main.categorychoices', verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='category',
            field=models.ManyToManyField(related_name='vacancys', to='main.categorychoices', verbose_name='категория'),
        ),
    ]
