# Generated by Django 4.2.7 on 2023-12-19 14:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_alter_curriculumvitae_job_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumvitae',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cv', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancy', to=settings.AUTH_USER_MODEL, verbose_name='компания'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='publish_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 19, 20, 44, 47, 733667), verbose_name='дата публикации'),
        ),
    ]
