# Generated by Django 4.2.7 on 2023-12-20 18:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_curriculumvitae_user_alter_vacancy_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='publish_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 21, 0, 44, 30, 524734), verbose_name='дата публикации'),
        ),
        migrations.CreateModel(
            name='VacancyResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='main.curriculumvitae', verbose_name='резюме')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_responses', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='main.vacancy', verbose_name='вакансия')),
            ],
            options={
                'verbose_name': 'отклик на вакансию',
                'verbose_name_plural': 'отклики на вакансию',
                'ordering': ('-id',),
            },
        ),
    ]
