# Generated by Django 4.2.7 on 2023-12-25 16:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_curriculumvitae_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculumvitae',
            name='category',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='category',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='publish_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 25, 22, 39, 30, 42731), verbose_name='дата публикации'),
        ),
        migrations.AddField(
            model_name='curriculumvitae',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.categorychoices', verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.categorychoices', verbose_name='категория'),
        ),
    ]
