# Generated by Django 4.2.7 on 2023-12-20 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_vacancy_publish_date_vacancyresponses'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='selery_currency',
            field=models.CharField(blank=True, choices=[('NOTSELECTED', 'Не выбрано'), ('KZT', 'Тенге'), ('RUB', 'Рубли'), ('USD', 'Доллары'), ('EUR', 'Евро'), ('CAD', 'Канадский доллар'), ('GBP', 'Британский фунт'), ('CNH', 'Китайский юань')], max_length=15, null=True, verbose_name='валюта'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='publish_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 21, 0, 47, 22, 368270), verbose_name='дата публикации'),
        ),
    ]
