# Generated by Django 4.2.7 on 2023-12-25 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_curriculumvitae_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='publish_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 26, 1, 16, 40, 117736), verbose_name='дата публикации'),
        ),
    ]
