# Generated by Django 4.2.7 on 2023-12-20 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_vacancy_selery_currency_alter_vacancy_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyresponses',
            name='datetime_response',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата и время отклика'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='publish_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 21, 0, 53, 13, 760897), verbose_name='дата публикации'),
        ),
    ]
