# Generated by Django 4.2.7 on 2023-12-20 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_vacancyresponses_datetime_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='publish_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 21, 0, 53, 17, 356160), verbose_name='дата публикации'),
        ),
    ]
