# Generated by Django 4.2.7 on 2023-12-20 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_vacancy_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='publish_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 12, 21, 0, 53, 22, 32219), verbose_name='дата публикации'),
        ),
    ]
